# Generated by Django 6.0.4 on 2026-04-22 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_vendedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('img', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Rubro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='apellido',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='codigo_postal',
            field=models.CharField(default='a', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendedor',
            name='apellido',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='ProveedorProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.producto')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.proveedor')),
            ],
            options={
                'unique_together': {('producto', 'proveedor')},
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='proveedores',
            field=models.ManyToManyField(through='core.ProveedorProducto', to='core.proveedor'),
        ),
        migrations.CreateModel(
            name='RubroProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.producto')),
                ('rubro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.rubro')),
            ],
            options={
                'unique_together': {('producto', 'rubro')},
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='rubros',
            field=models.ManyToManyField(through='core.RubroProducto', to='core.rubro'),
        ),
    ]
