# Generated by Django 6.0.4 on 2026-04-26 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_promocion_alter_envio_estado_envio_detallefactura_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='proveedorproducto',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='rubroproducto',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='envio',
            name='estado_envio',
            field=models.CharField(choices=[('recibido', 'Recibido'), ('preparacion', 'En preparación'), ('enviado', 'Enviado'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='recibido', max_length=20),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='productopromocion',
            constraint=models.UniqueConstraint(fields=('producto', 'promocion'), name='unique_producto_promocion'),
        ),
        migrations.AddConstraint(
            model_name='proveedorproducto',
            constraint=models.UniqueConstraint(fields=('producto', 'proveedor'), name='unique_producto_proveedor'),
        ),
        migrations.AddConstraint(
            model_name='rubroproducto',
            constraint=models.UniqueConstraint(fields=('producto', 'rubro'), name='unique_producto_rubro'),
        ),
    ]
